# Generated by Django 3.0.7 on 2020-12-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dangerlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('picture', models.TextField(blank=True)),
                ('is_impact_on_environment', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
                ('danger_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.DangerLevel')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
